### ISSUE TITLE
为何我调试的时候，页面上没有我的js代码？

### ISSUE THREAD

**Issue by ddxxll2008** [weexteam/weex-devtools-android#44]
为何我将devtools集成到自己的app中调试时，页面上看不到我的js代码呢？但是通过playground扫码就可以看到。求各位大神指导啊。
以下截图是我自己在app里集成devtools时的页面
<img width="514" alt="2017-01-18 10 02 36" src="https://cloud.githubusercontent.com/assets/18613575/22047981/45392b58-dd65-11e6-9849-b7acf53e708f.png">

<img width="1214" alt="2017-01-18 9 57 22" src="https://cloud.githubusercontent.com/assets/18613575/22047941/0b7eda52-dd65-11e6-9b77-fc7e9db1dc09.png">

最开始进入debug的时候，页面还会报错
<img width="1209" alt="2017-01-18 10 07 41" src="https://cloud.githubusercontent.com/assets/18613575/22048195/4b0bd5a2-dd66-11e6-837c-0d055e4f6dc1.png">

下面这张图是我用playground扫码得到的debug页面
![Uploading 屏幕快照 2017-01-18 上午10.11.52.png…]()

以下是我在Application里集成的代码
`initDebugEnvironment(true, "192.168.38.81"/*"DEBUG_SERVER_HOST"*/);`

`private void initDebugEnvironment(boolean enable, String host) {
		WXEnvironment.sRemoteDebugMode = enable;
		WXEnvironment.sRemoteDebugProxyUrl = "ws://" + host + ":8088/debugProxy/native";
	}`

（但是我没有做刷新广播的处理，对于loadWXfromService(mUri.toString());和loadWXfromLocal(true);还不是很清楚。下载了playground的源码，结果gradle一直在编译中，因为maven 1.4.1不能离线使用，尴尬。）

**Comment by dutlxq2014** [comment]
+1

**Comment by dutlxq2014** [comment]
知道原因了，当前页面需要监听weex framework重新初始化的广播，
LocalBroadcastManager.getInstance(this).registerReceiver(mReloadReceiver,new IntentFilter(WXSDKEngine.JS_FRAMEWORK_RELOAD));
接受到广播后重新创建当前页面的WeexInstance，重新加载就可以了，具体流程看一下playground的代码

**Comment by littleseven** [comment]
@ddxxll2008 问题解决掉了吗？如果还有问题，请贴一下集成的weex_inspector的版本

**Comment by ddxxll2008** [comment]
@dutlxq2014 
好的，有时间我来试一下~~

**Comment by ddxxll2008** [comment]
@littleseven 最近还没有弄这个呢，等我有时间来试下哈，谢谢大神关注~~

**Comment by ddxxll2008** [comment]
集成了最新版本的weex_inspector后，问题解决，可以看到js代码了。

compile 'com.taobao.android:weex_inspector:0.10.0.5@aar'

**Comment by ddxxll2008** [comment]
@littleseven 已经可以调试啦~~
