### ISSUE TITLE
如何hot refresh

### ISSUE THREAD

**Issue by LonerJimmy** [weexteam/weex-devtools-android#45]
如何在本地修改we代码，移动端可以立即执行，看到修改后的效果。playground代码中，我看到有这个函数，我这里hot refresh连接的是debug服务端口，但是没有效果。不知道weex hot refresh是需要新起一个服务呢，还是用debug、watch等服务端口呢

**Comment by littleseven** [comment]
weex deug xxx.we ,当修改we代码后保存即可触发refresh

**Comment by LonerJimmy** [comment]
使用weex xxx.we --qr，整个工程代码改变都可以触发refresh

**Comment by joewang1212** [comment]
以前做React Native，run android，会启动一个模拟器(修改实时刷新)，和chrome debug窗口. 在weex的世界里，一切有点麻烦。
